# Generated by Django 2.2.5 on 2019-11-04 00:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('item_price', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('bounty', models.FloatField()),
                ('location', models.CharField(max_length=50)),
                ('dateposted', models.DateField(auto_now_add=True)),
                ('daterequested', models.DateField()),
                ('cost', models.FloatField()),
                ('numitems', models.IntegerField()),
                ('shopper', models.CharField(max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Quantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_food', models.IntegerField(default=0)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Food')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Post')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='items',
            field=models.ManyToManyField(through='shop.Quantity', to='shop.Food'),
        ),
    ]
