# Generated by Django 2.2.5 on 2019-11-08 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20191103_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='general_location',
            field=models.CharField(choices=[('BICE', 'Bice House'), ('BOND', 'Bond House'), ('BROWN', 'Brown College'), ('COPELEY', 'Copeley Apartments'), ('SHEA', 'French House/Spanish House/Shea House'), ('GOOCH', 'Gooch Dillard/ Hereford'), ('GRANDMARC', 'GrandMarc At the Corner'), ('HEREFORD', 'Hereford College'), ('IRC', 'International Residential College'), ('JPA', 'JPA'), ('LAMBETH', 'Lambeth Field Apartments'), ('LARK', 'Lark on Main'), ('NEW_DORMS', 'New Dorms'), ('OLD_DORMS', 'Old Dorms'), ('PRESTON', 'Preston Avenue Area'), ('FLATS', 'The Flats at West Village'), ('LAWN', 'The Lawn'), ('STANDARD', 'The Standard')], default='JPA', max_length=100),
        ),
    ]
